// <auto-generated />
using System;
using G2CyHome.EntityConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20220416172100_device_type")]
    partial class device_type
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("G2CyHome.Systems.Entities.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("唯一标识");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_time")
                        .HasComment("删除时间");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("logo")
                        .HasComment("类型logo");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("name")
                        .HasComment("类型名称");

                    b.Property<string>("PicPath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("pic_path")
                        .HasComment("类型图片");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("remark")
                        .HasComment("备注信息");

                    b.HasKey("Id");

                    b.ToTable("systems_devicetype");

                    b
                        .HasComment("设备类型");
                });

            modelBuilder.Entity("G2CyHome.Systems.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("唯一标识");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_time")
                        .HasComment("删除时间");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasColumnName("name")
                        .HasComment("标签名称");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasColumnName("remark")
                        .HasComment("备注");

                    b.HasKey("Id");

                    b.ToTable("systems_label");

                    b
                        .HasComment("标签管理");
                });
#pragma warning restore 612, 618
        }
    }
}
