//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的映射，可新建文件“RoomConfiguration.cs”的分部类“public partial class RoomConfiguration”实现分部方法 EntityConfigurationAppend 进行扩展
// </auto-generated>
//
// <copyright file="RoomConfiguration.generated.cs" company="无">
//     
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using OSharp.Entity;

using G2CyHome.Systems.Entities;


namespace G2CyHome.EntityConfiguration.Systems
{
    /// <summary>
    /// 实体配置类：房间管理信息
    /// </summary>
    public partial class RoomConfiguration : EntityTypeConfigurationBase<Room, int>
    {
        /// <summary>
        /// 重写以实现实体类型各个属性的数据库配置
        /// </summary>
        /// <param name="builder">实体类型创建器</param>
        public override void Configure(EntityTypeBuilder<Room> builder)
        {
              //表名
              builder.ToTable("room").HasComment("房间管理");
              // 列名
              builder.Property(x => x.Id).HasColumnName("id").HasComment("唯一标识");
              builder.Property(x => x.Name).HasColumnName("name").HasComment("房间名称");
              builder.Property(x => x.Floor).HasColumnName("floor").HasComment("所在楼层");
              builder.Property(x => x.Remark).HasColumnName("remark").HasComment("备注信息");
              builder.Property(x => x.Logo).HasColumnName("logo").HasComment("房间logo");
              builder.Property(x => x.PicPath).HasColumnName("pic_path").HasComment("房间图片");
              builder.Property(x => x.Order).HasColumnName("order").HasComment("排序");

              builder.Property(x => x.CreatedTime).HasColumnName("created_time").HasComment("创建时间");

              builder.Property(x => x.CreatorId).HasColumnName("creator_id").HasComment("创建人id");

              builder.Property(x => x.LastUpdaterId).HasColumnName("last_updater_id").HasComment("更新者编号");
              builder.Property(x => x.LastUpdatedTime).HasColumnName("last_updated_time").HasComment("最后更新时间");

              builder.Property(x => x.DeletedTime).HasColumnName("deleted_time").HasComment("删除时间");
            EntityConfigurationAppend(builder);
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void EntityConfigurationAppend(EntityTypeBuilder<Room> builder);
    }
}
