//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“Room.cs”的分部类“public partial class Room”添加属性
// </auto-generated>
//
// <copyright file="Room.generated.cs" company="无">
//     
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace G2CyHome.Systems.Entities
{
    /// <summary>
    /// 实体类：房间管理信息
    /// </summary>
    [Description("房间管理信息")]
    [TableNamePrefix("systems")]
    public partial class Room : EntityBase<int>, ISoftDeletable, ICreatedTime, ICreationAudited<int>, IUpdateAudited<int>
    {
        /// <summary>
        /// 获取或设置 房间名称
        /// </summary>
        [DisplayName("房间名称"), Required]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 所在楼层
        /// </summary>
        [DisplayName("所在楼层")]
        public int Floor { get; set; }

        /// <summary>
        /// 获取或设置 备注信息
        /// </summary>
        [DisplayName("备注信息"), StringLength(100)]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 房间logo
        /// </summary>
        [DisplayName("房间logo"), StringLength(100)]
        public string Logo { get; set; }

        /// <summary>
        /// 获取或设置 房间图片
        /// </summary>
        [DisplayName("房间图片"), StringLength(1000)]
        public string PicPath { get; set; }

        /// <summary>
        /// 获取或设置 排序
        /// </summary>
        [DisplayName("排序")]
        public int Order { get; set; }

        /// <summary>
        /// 获取或设置 数据逻辑删除时间，为null表示正常数据，有值表示已逻辑删除，同时删除时间每次不同也能保证索引唯一性
        /// </summary>
        [DisplayName("删除时间")]
        public DateTime? DeletedTime { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 创建者编号
        /// </summary>
        [DisplayName("创建者编号")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 更新者编号
        /// </summary>
        [DisplayName("更新者编号")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 最后更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

    }
}

