// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 DeviceRecord 添加方法，可新建文件“DevicesServiceBase.DeviceRecord.cs”的分部类“public abstract partial class DevicesServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 DeviceRecord 的业务实现，可新建文件“DevicesService.DeviceRecord.cs”的分部类“public partial class DevicesService”对现有方法进行方法重写实现
//</auto-generated>
//
// <copyright file="DevicesServiceBase.DeviceRecord.generated.cs" company="无">
//    
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using G2CyHome.Devices.Dtos;
using G2CyHome.Devices.Entities;


namespace G2CyHome.Devices
{
    public abstract partial class DevicesServiceBase
    {
        /// <summary>
        /// 获取 设备记录信息查询数据集
        /// </summary>
        public virtual IQueryable<DeviceRecord> DeviceRecords
        {
            get { return DeviceRecordRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查设备记录信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的设备记录信息编号</param>
        /// <returns>设备记录信息是否存在</returns>
        public virtual Task<bool> CheckDeviceRecordExists(Expression<Func<DeviceRecord, bool>> predicate, Guid id = default(Guid))
        {
            return DeviceRecordRepository.CheckExistsAsync(predicate, id);
        }

    /// <summary>
    /// 添加设备记录信息
    /// </summary>
    /// <param name="dtos">要添加的设备记录信息DTO信息</param>
    /// <returns>业务操作结果</returns>
    public virtual Task<OperationResult> CreateDeviceRecords(params DeviceRecordCreateInput[] dtos)
    {
    Check.Validate<DeviceRecordCreateInput, Guid>(dtos, nameof(dtos));
    return DeviceRecordRepository.InsertAsync(dtos);
    }
  
    /// <summary>
    /// 更新设备记录信息
    /// </summary>
    /// <param name="dtos">包含更新信息的设备记录信息DTO信息</param>
    /// <returns>业务操作结果</returns>
    public virtual Task<OperationResult> UpdateDeviceRecords(params DeviceRecordUpdateInput[] dtos)
    {
    Check.Validate<DeviceRecordUpdateInput, Guid>(dtos, nameof(dtos));
    return DeviceRecordRepository.UpdateAsync(dtos);
    }
  
    /// <summary>
    /// 删除设备记录信息
    /// </summary>
    /// <param name="ids">要删除的设备记录信息编号</param>
    /// <returns>业务操作结果</returns>
    public virtual Task<OperationResult> DeleteDeviceRecords(params Guid[] ids)
    {
    Check.NotNull(ids, nameof(ids));
    return DeviceRecordRepository.DeleteAsync(ids);
    }
      }
}
