// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，请在控制器类型 SystemsService 进行继承重写
// </auto-generated>
//
// <copyright file="SystemsServiceBase.generated.cs" company="无">
//    
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Threading.Tasks;

using OSharp.Core.Systems;
using OSharp.Data;
using OSharp.Entity;
using OSharp.EventBuses;
using OSharp.Extensions;
using OSharp.Identity;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using G2CyHome.Systems.Dtos;
using G2CyHome.Systems.Entities;


namespace G2CyHome.Systems
{
    /// <summary>
    /// 业务实现基类：系统管理模块
    /// </summary>
    public abstract partial class SystemsServiceBase : ISystemsContract
    {
        /// <summary>
        /// 初始化一个<see cref="SystemsService"/>类型的新实例
        /// </summary>
        protected SystemsServiceBase(IServiceProvider provider)
        {
            ServiceProvider = provider;
            Logger = provider.GetLogger(GetType());
        }
    
        #region 属性

        /// <summary>
        /// 获取 服务提供者对象
        /// </summary>
        protected IServiceProvider ServiceProvider { get; }

        /// <summary>
        /// 获取 日志对象
        /// </summary>
        protected ILogger Logger { get; }

        /// <summary>
        /// 获取 房间管理信息仓储对象
        /// </summary>
        protected IRepository<Room, int> RoomRepository => ServiceProvider.GetRequiredService<IRepository<Room, int>>();

        /// <summary>
        /// 获取 标签管理信息仓储对象
        /// </summary>
        protected IRepository<Label, int> LabelRepository => ServiceProvider.GetRequiredService<IRepository<Label, int>>();

        /// <summary>
        /// 获取 设备类型信息仓储对象
        /// </summary>
        protected IRepository<DeviceType, int> DeviceTypeRepository => ServiceProvider.GetRequiredService<IRepository<DeviceType, int>>();

        /// <summary>
        /// 获取 设备标签关联信息仓储对象
        /// </summary>
        protected IRepository<DeviceLabel, int> DeviceLabelRepository => ServiceProvider.GetRequiredService<IRepository<DeviceLabel, int>>();
        /// <summary>
        /// 获取 菜单信息仓储对象
        /// </summary>
        protected IRepository<Menu, int> MenuInfoRepository => ServiceProvider.GetService<IRepository<Menu, int>>();

        /// <summary>
        /// 获取 事件总线
        /// </summary>
        protected IEventBus EventBus => ServiceProvider.GetService<IEventBus>();

        /// <summary>
        /// 获取 设置存储对象
        /// </summary>
        protected IKeyValueStore KeyValueStore => ServiceProvider.GetService<IKeyValueStore>();

        #endregion
    }
}
