// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，请在控制器类型 DevicesService 进行继承重写
// </auto-generated>
//
// <copyright file="DevicesServiceBase.generated.cs" company="无">
//    
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Threading.Tasks;

using OSharp.Core.Systems;
using OSharp.Data;
using OSharp.Entity;
using OSharp.EventBuses;
using OSharp.Extensions;
using OSharp.Identity;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using G2CyHome.Devices.Dtos;
using G2CyHome.Devices.Entities;


namespace G2CyHome.Devices
{
    /// <summary>
    /// 业务实现基类：设备管理模块
    /// </summary>
    public abstract partial class DevicesServiceBase : IDevicesContract
    {
        /// <summary>
        /// 初始化一个<see cref="DevicesService"/>类型的新实例
        /// </summary>
        protected DevicesServiceBase(IServiceProvider provider)
        {
            ServiceProvider = provider;
            Logger = provider.GetLogger(GetType());
        }
    
        #region 属性

        /// <summary>
        /// 获取 服务提供者对象
        /// </summary>
        protected IServiceProvider ServiceProvider { get; }

        /// <summary>
        /// 获取 日志对象
        /// </summary>
        protected ILogger Logger { get; }

        /// <summary>
        /// 获取 设备记录信息仓储对象
        /// </summary>
        protected IRepository<DeviceRecord, Guid> DeviceRecordRepository => ServiceProvider.GetRequiredService<IRepository<DeviceRecord, Guid>>();

        /// <summary>
        /// 获取 传感器数据信息仓储对象
        /// </summary>
        protected IRepository<SensorData, int> SensorDataRepository => ServiceProvider.GetRequiredService<IRepository<SensorData, int>>();

        /// <summary>
        /// 获取 事件总线
        /// </summary>
        protected IEventBus EventBus => ServiceProvider.GetService<IEventBus>();

        /// <summary>
        /// 获取 设置存储对象
        /// </summary>
        protected IKeyValueStore KeyValueStore => ServiceProvider.GetService<IKeyValueStore>();

        #endregion
    }
}
