//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的映射，可新建文件“DeviceRecordConfiguration.cs”的分部类“public partial class DeviceRecordConfiguration”实现分部方法 EntityConfigurationAppend 进行扩展
// </auto-generated>
//
// <copyright file="DeviceRecordConfiguration.generated.cs" company="无">
//     
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using OSharp.Entity;

using G2CyHome.Devices.Entities;
using G2CyHome.Systems.Entities;

namespace G2CyHome.EntityConfiguration.Devices
{
    /// <summary>
    /// 实体配置类：设备记录信息
    /// </summary>
    public partial class DeviceRecordConfiguration : EntityTypeConfigurationBase<DeviceRecord, Guid>
    {
        /// <summary>
        /// 重写以实现实体类型各个属性的数据库配置
        /// </summary>
        /// <param name="builder">实体类型创建器</param>
        public override void Configure(EntityTypeBuilder<DeviceRecord> builder)
        {
              //表名
              builder.ToTable("devicerecord").HasComment("设备记录");
              // 列名
              builder.Property(x => x.Id).HasColumnName("id").HasComment("唯一标识");
              builder.Property(x => x.Name).HasColumnName("name").HasComment("设备名称");
              builder.Property(x => x.RoomId).HasColumnName("room_id").HasComment("所属房间");
              builder.Property(x => x.DevicetypeId).HasColumnName("devicetype_id").HasComment("设备类型id");
              builder.Property(x => x.DeviceIdentity).HasColumnName("device_identity").HasComment("设备标识");
              builder.Property(x => x.Status).HasColumnName("status").HasComment("设备状态");
              builder.Property(x => x.ControlMode).HasColumnName("control_mode").HasComment("控制方式");
              builder.Property(x => x.Descript).HasColumnName("descript").HasComment("设备描述");

              builder.Property(x => x.CreatedTime).HasColumnName("created_time").HasComment("创建时间");

              builder.Property(x => x.DeletedTime).HasColumnName("deleted_time").HasComment("删除时间");
            EntityConfigurationAppend(builder);
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void EntityConfigurationAppend(EntityTypeBuilder<DeviceRecord> builder);
    }
}
