//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的映射，可新建文件“SensorDataConfiguration.cs”的分部类“public partial class SensorDataConfiguration”实现分部方法 EntityConfigurationAppend 进行扩展
// </auto-generated>
//
// <copyright file="SensorDataConfiguration.generated.cs" company="无">
//     
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using OSharp.Entity;

using G2CyHome.Devices.Entities;


namespace G2CyHome.EntityConfiguration.Devices
{
    /// <summary>
    /// 实体配置类：传感器数据信息
    /// </summary>
    public partial class SensorDataConfiguration : EntityTypeConfigurationBase<SensorData, int>
    {
        /// <summary>
        /// 重写以实现实体类型各个属性的数据库配置
        /// </summary>
        /// <param name="builder">实体类型创建器</param>
        public override void Configure(EntityTypeBuilder<SensorData> builder)
        {
              //表名
              builder.ToTable("sensordata").HasComment("传感器数据");
              // 列名
              builder.Property(x => x.Id).HasColumnName("id").HasComment("唯一标识");
              builder.Property(x => x.DeviceIdentity).HasColumnName("device_identity").HasComment("设备标识");
              builder.Property(x => x.Data).HasColumnName("data").HasComment("数据信息");

              builder.Property(x => x.CreatedTime).HasColumnName("created_time").HasComment("创建时间");
            EntityConfigurationAppend(builder);
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void EntityConfigurationAppend(EntityTypeBuilder<SensorData> builder);
    }
}
