//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“SensorData.cs”的分部类“public partial class SensorData”添加属性
// </auto-generated>
//
// <copyright file="SensorData.generated.cs" company="无">
//     
// </copyright>
// <site></site>
// <last-editor>ggcy</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace G2CyHome.Devices.Entities
{
    /// <summary>
    /// 实体类：传感器数据信息
    /// </summary>
    [Description("传感器数据信息")]
    [TableNamePrefix("devices")]
    public partial class SensorData : EntityBase<int>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 设备标识
        /// </summary>
        [DisplayName("设备标识")]
        public string DeviceIdentity { get; set; }

        /// <summary>
        /// 获取或设置 数据信息
        /// </summary>
        [DisplayName("数据信息")]
        public string Data { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

    }
}

